datadog:
  admissionController: true
  instrumentation: autoInjection
  tracerVersion: latest
  appSec: false
  profiling: false
application:
  service:
  env: lab
  version: 0.1
  url: https://github.com/yafernandes/java-playground/releases/latest/download/playground.war
  endpoints:
  - /playground/servletAPI4
  appServer:
    image: tomcat:9.0
    webappsDir: /usr/local/tomcat/webapps
    port: 8080
loadrunner:
  startDelay: 5
  interval:
    minimum: 2
    maximum: 5