apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        admission.datadoghq.com/enabled: "true"
        tags.datadoghq.com/env:  {{ .Values.application.env }}
        tags.datadoghq.com/service: {{ .Values.application.service | default .Release.Name }}
        tags.datadoghq.com/version: {{ .Values.application.version | quote }}
      annotations:
      {{- if eq .Values.datadog.instrumentation "autoInstrumentation" }}
        admission.datadoghq.com/java-lib.version: {{ .Values.datadog.tracerVersion | quote }}
      {{- end }}
    spec:
      initContainers:
        - name: init-copy-war
          image: yaalexf/servlet:war
          imagePullPolicy: Always
          command: ["sh", "-c", "cp /build/* /webapps"]
          volumeMounts:
            - mountPath: /webapps
              name: webapps
        {{- if eq .Values.datadog.instrumentation "otel" }}
        - name: init-copy-otel
          image: alpine
          command: ["sh", "-c", "wget -O /otel/opentelemetry-javaagent.jar https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar"]
          volumeMounts:
            - mountPath: /otel
              name: otel
        {{- end }}
      containers:
        - name: appserver
          image: {{ .Values.application.appServer.image | quote }}
          env:
            - name: DD_APPSEC_ENABLED
              value: {{ .Values.datadog.appSec | quote }}
            - name: DD_PROFILING_ENABLED
              value: {{ .Values.datadog.profiling | quote }}
            {{- if eq .Values.datadog.instrumentation "otel" }}
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/otel/opentelemetry-javaagent.jar"
            - name: OTEL_COLLECTOR_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://$(OTEL_COLLECTOR_HOST):4317/
            - name: OTEL_SERVICE_NAME
              value: {{ .Values.application.service | default .Release.Name }}
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: deployment.environment={{ .Values.application.env }},service.version={{ .Values.application.version }}
            {{- end }}
          volumeMounts:
            - mountPath: {{ .Values.application.appServer.webappsDir }}
              name: webapps
            {{- if eq .Values.datadog.instrumentation "otel" }}
            - mountPath: /otel
              name: otel
            {{- end }}
      volumes:
        - name: webapps
          emptyDir:
        {{- if eq .Values.datadog.instrumentation "otel" }}
        - name: otel
          emptyDir:
        {{ end }}